### ISSUE TITLE
Call crawlers for different news sources in separate threads 

### ISSUE THREAD

**Issue by nuuuwan** [LSFLK/GIG-Scripts#15]
# Problem

Currently, the crawlers for different news sources are called serially (@umayangag please verify this claim - it was based on a rough look at the code). This means that a crash on one source will stop the remaining sources being crawled. 

# Solution

Call crawlers for different news sources in separate threads

https://github.com/LSFLK/GIG-Scripts/blob/f37a4a8b885532764d2a129b1cf27461d4d3cc0e/kavuda/crawl.go#L16-L20

**Comment by umayangag** [comment]
Yes currently they run serially. My concern was that since we have limited server capacity on dev server if we run the crawlers parallely it would overload the server. Even now the scripts runs for around 20 minutes and the server memory hits the maximum. I will separate them and run them at different timeframes so the issue can be resolved
